
import Hero from '@/component/hero'
import './globals.css'
export const metadata = {
  title: 'agenone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body >
        <Hero/>
        {children}
        </body>
    </html>
  )
}

