<<<<<<< HEAD

import Hero from '@/component/hero'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body >
        <Hero/>
        {children}
        </body>
    </html>
  )
}
=======
import ClientComponent from './component/ClientComponent'
import Hero from './component/hero'
import Service from './component/services'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body >
        {children}
        </body>
    </html>
  )
}
>>>>>>> d0dab96 (first commit)
